//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMP.Work.CommunicatorPSDTU.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NetErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMP.Work.CommunicatorPSDTU.Common.Resources.NetErrors", typeof(NetErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software released the connection interruption.
        ///The established connection was interrupted by software on the host computer, possibly due to a data transfer timeout or protocol error..
        /// </summary>
        internal static string WSAECONNABORTED {
            get {
                return ResourceManager.GetString("WSAECONNABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection refused.
        ///Could not connect because the target computer refused it. Usually this happens when you try to connect to a service that is inactive on an external node, that is, to a service without a running server application..
        /// </summary>
        internal static string WSAECONNREFUSED {
            get {
                return ResourceManager.GetString("WSAECONNREFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network is down.
        ///The socket operation detected a network outage. This may indicate serious problems with the network system (the protocol stack that powers the Windows Sockets DLL), the network interface, or the local network itself..
        /// </summary>
        internal static string WSAENETDOWN {
            get {
                return ResourceManager.GetString("WSAENETDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out.
        ///The connection attempt failed because the connected party did not respond properly after some time, or the established connection failed because the connected host failed to respond..
        /// </summary>
        internal static string WSAETIMEDOUT {
            get {
                return ResourceManager.GetString("WSAETIMEDOUT", resourceCulture);
            }
        }
    }
}
