//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMP.Work.CommunicatorPSDTU.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertiesNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMP.Work.CommunicatorPSDTU.Common.Resources.PropertiesNames", typeof(PropertiesNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apn.
        /// </summary>
        public static string ApnProperty {
            get {
                return ResourceManager.GetString("ApnProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware date.
        /// </summary>
        public static string DeviceFirmwareDateProperty {
            get {
                return ResourceManager.GetString("DeviceFirmwareDateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version.
        /// </summary>
        public static string DeviceFirmwareVersionProperty {
            get {
                return ResourceManager.GetString("DeviceFirmwareVersionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type.
        /// </summary>
        public static string DeviceNameProperty {
            get {
                return ResourceManager.GetString("DeviceNameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network type.
        /// </summary>
        public static string DeviceNetworkTypeProperty {
            get {
                return ResourceManager.GetString("DeviceNetworkTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 bit.
        /// </summary>
        public static string EightBits {
            get {
                return ResourceManager.GetString("EightBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip address.
        /// </summary>
        public static string IpAddressProperty {
            get {
                return ResourceManager.GetString("IpAddressProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginProperty {
            get {
                return ResourceManager.GetString("LoginProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string NameProperty {
            get {
                return ResourceManager.GetString("NameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal strength.
        /// </summary>
        public static string NetLevelProperty {
            get {
                return ResourceManager.GetString("NetLevelProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net mode.
        /// </summary>
        public static string NetModeProperty {
            get {
                return ResourceManager.GetString("NetModeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of connection attempts.
        /// </summary>
        public static string NumberOfConnectionAttempsProperty {
            get {
                return ResourceManager.GetString("NumberOfConnectionAttempsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to even.
        /// </summary>
        public static string ParityEven {
            get {
                return ResourceManager.GetString("ParityEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string ParityNone {
            get {
                return ResourceManager.GetString("ParityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to odd.
        /// </summary>
        public static string ParityOdd {
            get {
                return ResourceManager.GetString("ParityOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordProperty {
            get {
                return ResourceManager.GetString("PasswordProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port.
        /// </summary>
        public static string PortProperty {
            get {
                return ResourceManager.GetString("PortProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 bit.
        /// </summary>
        public static string SevenBits {
            get {
                return ResourceManager.GetString("SevenBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one.
        /// </summary>
        public static string StopBitsOne {
            get {
                return ResourceManager.GetString("StopBitsOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two.
        /// </summary>
        public static string StopBitsTwo {
            get {
                return ResourceManager.GetString("StopBitsTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdog timer in minutes.
        /// </summary>
        public static string WatchdogTimerProperty {
            get {
                return ResourceManager.GetString("WatchdogTimerProperty", resourceCulture);
            }
        }
    }
}
