//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMP.Work.CommunicatorPSDTU.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMP.Work.CommunicatorPSDTU.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL_COMMAND_HEADER {
            get {
                return ResourceManager.GetString("CANCEL_COMMAND_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading signal strength.
        /// </summary>
        public static string CHECK_NET_LEVEL_MESSAGE {
            get {
                return ResourceManager.GetString("CHECK_NET_LEVEL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string CONNECT_COMMAND_HEADER {
            get {
                return ResourceManager.GetString("CONNECT_COMMAND_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error..
        /// </summary>
        public static string CONNECT_ERROR {
            get {
                return ResourceManager.GetString("CONNECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected. Data readed..
        /// </summary>
        public static string CONNECTED_DATA_READED {
            get {
                return ResourceManager.GetString("CONNECTED_DATA_READED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wating: enter IP address..
        /// </summary>
        public static string DEFAULT_NO_IP_ADDRESS_MESSAGE {
            get {
                return ResourceManager.GetString("DEFAULT_NO_IP_ADDRESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready: waiting for connect..
        /// </summary>
        public static string DEFAULT_READY_MESSAGE {
            get {
                return ResourceManager.GetString("DEFAULT_READY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll devices.
        /// </summary>
        public static string DEVICES_CHECKING {
            get {
                return ResourceManager.GetString("DEVICES_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string DISCONNECT_COMMAND_HEADER {
            get {
                return ResourceManager.GetString("DISCONNECT_COMMAND_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data..
        /// </summary>
        public static string ERROR_DATA_READING {
            get {
                return ResourceManager.GetString("ERROR_DATA_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured..
        /// </summary>
        public static string ERROR_OCCURED {
            get {
                return ResourceManager.GetString("ERROR_OCCURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured. New device settings not saved..
        /// </summary>
        public static string ERROR_OCCURED_NEW_DEVICE_SETTINGS_NOT_SAVED {
            get {
                return ResourceManager.GetString("ERROR_OCCURED_NEW_DEVICE_SETTINGS_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish connection..
        /// </summary>
        public static string FAILED_TO_ESTABLISH_CONNECTION {
            get {
                return ResourceManager.GetString("FAILED_TO_ESTABLISH_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish connection. Operation cancelled..
        /// </summary>
        public static string FAILED_TO_ESTABLISH_CONNECTION_CANCELLED {
            get {
                return ResourceManager.GetString("FAILED_TO_ESTABLISH_CONNECTION_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed. Timed out..
        /// </summary>
        public static string FAILED_TO_ESTABLISH_CONNECTION_TIMEOUT {
            get {
                return ResourceManager.GetString("FAILED_TO_ESTABLISH_CONNECTION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid response was received from the device. This may be an unsupported device..
        /// </summary>
        public static string InvalidAnswerUnknownDevice {
            get {
                return ResourceManager.GetString("InvalidAnswerUnknownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} lines..
        /// </summary>
        public static string LOADED_N_LINES {
            get {
                return ResourceManager.GetString("LOADED_N_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No settings!.
        /// </summary>
        public static string NEW_DEVICE_SETTINGS_IS_NOT_DEFINED {
            get {
                return ResourceManager.GetString("NEW_DEVICE_SETTINGS_IS_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving settings ....
        /// </summary>
        public static string NEW_DEVICE_SETTINGS_IS_SAVING {
            get {
                return ResourceManager.GetString("NEW_DEVICE_SETTINGS_IS_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New device settings saved..
        /// </summary>
        public static string NEW_DEVICE_SETTINGS_SAVED {
            get {
                return ResourceManager.GetString("NEW_DEVICE_SETTINGS_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection..
        /// </summary>
        public static string NOT_CONNECTED_DESCRIPTION {
            get {
                return ResourceManager.GetString("NOT_CONNECTED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled..
        /// </summary>
        public static string OPERATION_CANCELED {
            get {
                return ResourceManager.GetString("OPERATION_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelling ....
        /// </summary>
        public static string OPERATION_CANCELLING {
            get {
                return ResourceManager.GetString("OPERATION_CANCELLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} seconds passed.
        /// </summary>
        public static string PASSED_N_SECONDS {
            get {
                return ResourceManager.GetString("PASSED_N_SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped {0} lines..
        /// </summary>
        public static string SKIPPED_N_LINES {
            get {
                return ResourceManager.GetString("SKIPPED_N_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start devices check..
        /// </summary>
        public static string START_DEVICES_CHECK {
            get {
                return ResourceManager.GetString("START_DEVICES_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a timer to update the signal level value..
        /// </summary>
        public static string STARTING_UPDATE_NET_STRENGTH {
            get {
                return ResourceManager.GetString("STARTING_UPDATE_NET_STRENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to {0}:{1}..
        /// </summary>
        public static string SUCCESSFULLY_CONNECTED_TO {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_CONNECTED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try connect to {0}:{1} ....
        /// </summary>
        public static string TRY_TO_CONNECT_IP_AND_PORT {
            get {
                return ResourceManager.GetString("TRY_TO_CONNECT_IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ? unknown ?.
        /// </summary>
        public static string UnknownData {
            get {
                return ResourceManager.GetString("UnknownData", resourceCulture);
            }
        }
    }
}
