//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMP.Work.CommunicatorPSDTU.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI_strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMP.Work.CommunicatorPSDTU.Common.Resources.UI_strings", typeof(UI_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attempt #.
        /// </summary>
        public static string Attempt {
            get {
                return ResourceManager.GetString("Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_ok_content {
            get {
                return ResourceManager.GetString("Button_ok_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection with devices.
        /// </summary>
        public static string Check_devices_tab_header {
            get {
                return ResourceManager.GetString("Check_devices_tab_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list.
        /// </summary>
        public static string CheckContent_button_clear_list {
            get {
                return ResourceManager.GetString("CheckContent_button_clear_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CheckContent_button_copy_to_clipboard {
            get {
                return ResourceManager.GetString("CheckContent_button_copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the result to an Excel file.
        /// </summary>
        public static string CheckContent_button_copy_to_excel {
            get {
                return ResourceManager.GetString("CheckContent_button_copy_to_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        public static string CheckContent_button_paste_from_clipboard {
            get {
                return ResourceManager.GetString("CheckContent_button_paste_from_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from Excel file.
        /// </summary>
        public static string CheckContent_button_paste_from_excel {
            get {
                return ResourceManager.GetString("CheckContent_button_paste_from_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Excel file settings.
        /// </summary>
        public static string CheckContent_button_setup_excel {
            get {
                return ResourceManager.GetString("CheckContent_button_setup_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string CheckContent_expander_operations_header {
            get {
                return ResourceManager.GetString("CheckContent_expander_operations_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CheckContent_grid_column_description {
            get {
                return ResourceManager.GetString("CheckContent_grid_column_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type.
        /// </summary>
        public static string CheckContent_grid_column_device_type {
            get {
                return ResourceManager.GetString("CheckContent_grid_column_device_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version.
        /// </summary>
        public static string CheckContent_grid_column_firmware_date {
            get {
                return ResourceManager.GetString("CheckContent_grid_column_firmware_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware date.
        /// </summary>
        public static string CheckContent_grid_column_firmware_version {
            get {
                return ResourceManager.GetString("CheckContent_grid_column_firmware_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        public static string CheckContent_grid_column_ip_address {
            get {
                return ResourceManager.GetString("CheckContent_grid_column_ip_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network mode.
        /// </summary>
        public static string CheckContent_grid_column_net_mode {
            get {
                return ResourceManager.GetString("CheckContent_grid_column_net_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of connection attempts.
        /// </summary>
        public static string CheckContent_grid_column_number_of_retries {
            get {
                return ResourceManager.GetString("CheckContent_grid_column_number_of_retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal level.
        /// </summary>
        public static string CheckContent_grid_column_signal_level {
            get {
                return ResourceManager.GetString("CheckContent_grid_column_signal_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description.
        /// </summary>
        public static string CheckContent_short_description_header {
            get {
                return ResourceManager.GetString("CheckContent_short_description_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this mode, you can query a list of controllers or communicators.
        ///The list can be pasted from the clipboard. The clipboard should contain a table with two columns: &apos;Description&apos; and &apos;IP address&apos;.
        ///A ready-made Excel table can also be used. The results can be saved in it..
        /// </summary>
        public static string CheckContent_short_description_text {
            get {
                return ResourceManager.GetString("CheckContent_short_description_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed checking {0} of {1} – {2:N1}..
        /// </summary>
        public static string Checking_devices_progress {
            get {
                return ResourceManager.GetString("Checking_devices_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking &apos;{0}&apos; – attempt #{1}..
        /// </summary>
        public static string Checking_devices_state {
            get {
                return ResourceManager.GetString("Checking_devices_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking signal level and connection type....
        /// </summary>
        public static string CheckingSignalLevelAndConnectionType {
            get {
                return ResourceManager.GetString("CheckingSignalLevelAndConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established..
        /// </summary>
        public static string ConnectionEstablished {
            get {
                return ResourceManager.GetString("ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection parameters.
        /// </summary>
        public static string ConnectionParamsContent_info {
            get {
                return ResourceManager.GetString("ConnectionParamsContent_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout, seconds.
        /// </summary>
        public static string ConnectionParamsContent_label_connection_timeout {
            get {
                return ResourceManager.GetString("ConnectionParamsContent_label_connection_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language.
        /// </summary>
        public static string ConnectionParamsContent_label_language {
            get {
                return ResourceManager.GetString("ConnectionParamsContent_label_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal level check interval, ms.
        /// </summary>
        public static string ConnectionParamsContent_label_netStrengthCheckInterval {
            get {
                return ResourceManager.GetString("ConnectionParamsContent_label_netStrengthCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause between attempts, milliseconds.
        /// </summary>
        public static string ConnectionParamsContent_label_pause {
            get {
                return ResourceManager.GetString("ConnectionParamsContent_label_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response waiting time, seconds.
        /// </summary>
        public static string ConnectionParamsContent_label_response_timeout {
            get {
                return ResourceManager.GetString("ConnectionParamsContent_label_response_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts:.
        /// </summary>
        public static string ConnectionParamsContent_label_retries {
            get {
                return ResourceManager.GetString("ConnectionParamsContent_label_retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fluent theme.
        /// </summary>
        public static string ConnectionParamsContent_label_use_fluent {
            get {
                return ResourceManager.GetString("ConnectionParamsContent_label_use_fluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI interface.
        /// </summary>
        public static string ConnectionParamsContent_section_interface {
            get {
                return ResourceManager.GetString("ConnectionParamsContent_section_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trus Mikhail Petrovich.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current mode.
        /// </summary>
        public static string CurrentState_current_mode {
            get {
                return ResourceManager.GetString("CurrentState_current_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to db.
        /// </summary>
        public static string CurrentState_db {
            get {
                return ResourceManager.GetString("CurrentState_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from:.
        /// </summary>
        public static string CurrentState_label_from {
            get {
                return ResourceManager.GetString("CurrentState_label_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to priority:.
        /// </summary>
        public static string CurrentState_label_net_priority {
            get {
                return ResourceManager.GetString("CurrentState_label_net_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range:.
        /// </summary>
        public static string CurrentState_label_net_range {
            get {
                return ResourceManager.GetString("CurrentState_label_net_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet.
        /// </summary>
        public static string CurrentState_label_subnet {
            get {
                return ResourceManager.GetString("CurrentState_label_subnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string CurrentState_label_type {
            get {
                return ResourceManager.GetString("CurrentState_label_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version:.
        /// </summary>
        public static string CurrentState_label_version {
            get {
                return ResourceManager.GetString("CurrentState_label_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signal level:.
        /// </summary>
        public static string CurrentState_signal_level {
            get {
                return ResourceManager.GetString("CurrentState_signal_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device_tab_header {
            get {
                return ResourceManager.GetString("Device_tab_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function is not supported by the device or an invalid response was received from the device..
        /// </summary>
        public static string Function_not_supported_or_no_data {
            get {
                return ResourceManager.GetString("Function_not_supported_or_no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting data:.
        /// </summary>
        public static string GettingData {
            get {
                return ResourceManager.GetString("GettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping ....
        /// </summary>
        public static string IS_CANCELLING_COMMAND_HEADER {
            get {
                return ResourceManager.GetString("IS_CANCELLING_COMMAND_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writing new device configuration....
        /// </summary>
        public static string IsWritingNewDeviceConfiguration {
            get {
                return ResourceManager.GetString("IsWritingNewDeviceConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility is designed to read and change the settings of controllers and communicators produced by the branch &quot;PSDTU&quot; of RUE &quot;Grodnoenergo&quot;..
        /// </summary>
        public static string Main_window_description {
            get {
                return ResourceManager.GetString("Main_window_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicator and controller check utility.
        /// </summary>
        public static string Main_window_title {
            get {
                return ResourceManager.GetString("Main_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address:.
        /// </summary>
        public static string MainContent_device_ip_address {
            get {
                return ResourceManager.GetString("MainContent_device_ip_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MainContent_tab_current_state {
            get {
                return ResourceManager.GetString("MainContent_tab_current_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network settings.
        /// </summary>
        public static string MainContent_tab_network_config {
            get {
                return ResourceManager.GetString("MainContent_tab_network_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS485 settings.
        /// </summary>
        public static string MainContent_tab_rs485_config {
            get {
                return ResourceManager.GetString("MainContent_tab_rs485_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum field length is 16 characters.
        /// </summary>
        public static string Max_field_length_16_chars {
            get {
                return ResourceManager.GetString("Max_field_length_16_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum field length is 32 characters.
        /// </summary>
        public static string Max_field_length_32_chars {
            get {
                return ResourceManager.GetString("Max_field_length_32_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apn name.
        /// </summary>
        public static string NetworkConfig_label_apn {
            get {
                return ResourceManager.GetString("NetworkConfig_label_apn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apn password.
        /// </summary>
        public static string NetworkConfig_label_apn_password {
            get {
                return ResourceManager.GetString("NetworkConfig_label_apn_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apn user name.
        /// </summary>
        public static string NetworkConfig_label_apn_user {
            get {
                return ResourceManager.GetString("NetworkConfig_label_apn_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string NetworkConfig_label_minutes {
            get {
                return ResourceManager.GetString("NetworkConfig_label_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port.
        /// </summary>
        public static string NetworkConfig_label_tcp_port {
            get {
                return ResourceManager.GetString("NetworkConfig_label_tcp_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdog timer in minutes.
        /// </summary>
        public static string NetworkConfig_label_watchdog_timer {
            get {
                return ResourceManager.GetString("NetworkConfig_label_watchdog_timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (used to connect to the device). The maximum value is 65535..
        /// </summary>
        public static string NetworkConfig_tcp_port_tooltip {
            get {
                return ResourceManager.GetString("NetworkConfig_tcp_port_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause between requests.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading device configuration....
        /// </summary>
        public static string ReadingDeviceConfiguration {
            get {
                return ResourceManager.GetString("ReadingDeviceConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading network configuration....
        /// </summary>
        public static string ReadingNetworkConfiguration {
            get {
                return ResourceManager.GetString("ReadingNetworkConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading version....
        /// </summary>
        public static string ReadingVersion {
            get {
                return ResourceManager.GetString("ReadingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data transfer rate.
        /// </summary>
        public static string Rs485Config_label_baudrate {
            get {
                return ResourceManager.GetString("Rs485Config_label_baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of data bits.
        /// </summary>
        public static string Rs485Config_label_bits {
            get {
                return ResourceManager.GetString("Rs485Config_label_bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string Rs485Config_label_parity {
            get {
                return ResourceManager.GetString("Rs485Config_label_parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of stop bits.
        /// </summary>
        public static string Rs485Config_label_stop_bits {
            get {
                return ResourceManager.GetString("Rs485Config_label_stop_bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port Settings (RS485).
        /// </summary>
        public static string Rs485Config_tooltip {
            get {
                return ResourceManager.GetString("Rs485Config_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending data:.
        /// </summary>
        public static string SendingData {
            get {
                return ResourceManager.GetString("SendingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string Settings_tab_header {
            get {
                return ResourceManager.GetString("Settings_tab_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start check.
        /// </summary>
        public static string START_CHECK_DEVICES_COMMAND_HEADER {
            get {
                return ResourceManager.GetString("START_CHECK_DEVICES_COMMAND_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop check.
        /// </summary>
        public static string STOP_CHECK_DEVICES_COMMAND_HEADER {
            get {
                return ResourceManager.GetString("STOP_CHECK_DEVICES_COMMAND_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the parameters to the device.
        /// </summary>
        public static string Write_settings {
            get {
                return ResourceManager.GetString("Write_settings", resourceCulture);
            }
        }
    }
}
