//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMP.Work.CommunicatorPSDTU.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatingErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatingErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMP.Work.CommunicatorPSDTU.Common.Resources.ValidatingErrors", typeof(ValidatingErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a required field..
        /// </summary>
        public static string ItIsARequiredField {
            get {
                return ResourceManager.GetString("ItIsARequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum field length is 100 characters.
        /// </summary>
        public static string MaxLengthHasBeenExceeded100 {
            get {
                return ResourceManager.GetString("MaxLengthHasBeenExceeded100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum field length is 16 characters.
        /// </summary>
        public static string MaxLengthHasBeenExceeded16 {
            get {
                return ResourceManager.GetString("MaxLengthHasBeenExceeded16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum field length is 32 characters.
        /// </summary>
        public static string MaxLengthHasBeenExceeded32 {
            get {
                return ResourceManager.GetString("MaxLengthHasBeenExceeded32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum field length is 6 characters.
        /// </summary>
        public static string MaxLengthHasBeenExceeded6 {
            get {
                return ResourceManager.GetString("MaxLengthHasBeenExceeded6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port number must be between 1 and 65535..
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between 1001 and 65535..
        /// </summary>
        public static string PortValueValidationMessage {
            get {
                return ResourceManager.GetString("PortValueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be empty..
        /// </summary>
        public static string ValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between 1 and 99..
        /// </summary>
        public static string WatchdogTimerValueValidationMessage {
            get {
                return ResourceManager.GetString("WatchdogTimerValueValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter 4 numbers from 0 to 254, separated by a period..
        /// </summary>
        public static string YouMustEnter4NumbersDividedByPeriod {
            get {
                return ResourceManager.GetString("YouMustEnter4NumbersDividedByPeriod", resourceCulture);
            }
        }
    }
}
